name: Publish Packages

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Configure NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish Packages
        run: |
          for pkg in packages/*; do
            if [ -f "$pkg/package.json" ]; then
              # Set version to 0.0.1
              jq '.version = "0.0.1"' "$pkg/package.json" > tmp.json && mv tmp.json "$pkg/package.json"
              cd $pkg
              bun publish --access public
              cd ../..
            fi
          done