name: Publish Packages

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Publish create-h4-app
        run: |
          cd packages/create-h4-app
          jq '.version = "0.0.3"' "package.json" > tmp.json && mv tmp.json "package.json"
          bun publish --dry-run --auth-type legacy
          cd ../..

      - name: Publish core
        run: |
          cd packages/core
          jq '.version = "0.0.3"' "package.json" > tmp.json && mv tmp.json "package.json"
          bun publish --dry-run --auth-type legacy
          cd ../..

      - name: Publish jobs
        run: |
          cd packages/jobs
          jq '.version = "0.0.3"' "package.json" > tmp.json && mv tmp.json "package.json"
          bun publish --dry-run --auth-type legacy
          cd ../..

      - name: Publish queue
        run: |
          cd packages/queue
          jq '.version = "0.0.3"' "package.json" > tmp.json && mv tmp.json "package.json"
          bun publish --dry-run --auth-type legacy
          cd ../..

      - name: Publish scheduler
        run: |
          cd packages/scheduler
          jq '.version = "0.0.3"' "package.json" > tmp.json && mv tmp.json "package.json"
          bun publish --dry-run --auth-type legacy
          cd ../..

      - name: Publish models
        run: |
          cd packages/models
          jq '.version = "0.0.3"' "package.json" > tmp.json && mv tmp.json "package.json"
          bun publish --dry-run --auth-type legacy
          cd ../..

      - name: Publish server
        run: |
          cd packages/server
          jq '.version = "0.0.3"' "package.json" > tmp.json && mv tmp.json "package.json"
          bun publish --dry-run --auth-type legacy
          cd ../..